### ISSUE TITLE
你好，询问一下关于amap2.0 使用 AMapLoader 加载 AMapUI 插件的方式

### ISSUE THREAD

**Issue by xiangshu233** [vita2333/vmap#3]
官方只有这一种[示例](https://lbs.amap.com/api/amap-ui/demos/amapui-amaploader/amapui-amaploader1)，我按照它的示例来确实可以打印出改示例，但是我修改成轨迹展示则出现了报错，请问是我的引用方式不对吗，网上并没有这里解答，只得在这里询问，以下是我的加载代码
`  methods: {
    initAMap() {
      AMapLoader.load({
        key: "a0fe39f6c90ba997c0833b6b1cd00bfd", // 申请好的Web端开发者Key，首次调用 load 时必填
        version: "2.0", // 指定要加载的 JSAPI 的版本，缺省时默认为 1.4.15
        plugins: [], // 需要使用的的插件列表，如比例尺'AMap.Scale'等
        AMapUI: {
          // 是否加载 AMapUI，缺省不加载
          version: "1.1", // AMapUI 缺省 1.1
          plugins:['overlay/SimpleMarker', 'ui/misc/PathSimplifier'], // 需要加载的 AMapUI ui插件
        }
      })
        .then((AMap) => {
          this.initAMapSuccess(AMap);

        })
        .catch((e) => {
          console.log(e);
        });  
    },

    initAMapSuccess(AMap) {
      this.map = new AMap.Map('container', {
          zoom:17,// 级别
          center: [117.215749, 31.845937],// 中心点坐标
          viewMode: '3D',
      });

      console.log('2222:',  new AMapUI.PathSimplifier()); // 打印报错
      console.log('3333:', new AMapUI.SimpleMarker());  // 可以打印出实例

    }
  },`

**Comment by yuanbolin** [comment]
请问解决了吗,这个AMapUI从哪来的?

**Comment by xiangshu233** [comment]
问题已经解决了，谢谢


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 苑博林<mailto:notifications@github.com>
发送时间: 2020年12月21日 10:47
收件人: vita2333/vmap<mailto:vmap@noreply.github.com>
抄送: 傲慢或香橙<mailto:xiangshu233@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [vita2333/vmap] 你好，询问一下关于amap2.0 使用 AMapLoader 加载 AMapUI 插件的方式 (#3)


请问解决了吗,这个AMapUI从哪来的?

―

**Comment by yuanbolin** [comment]
OK,我也刚解决
